/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=.dev.vars.example --include-runtime=false --strict-vars=false --env-interface=WorkerBindings` (hash: 55471dcd71d7117c01b4d0213a20d584)
interface __BaseEnv_WorkerBindings {
	GEMINI_BL: string;
	GEMINI_ORIGIN: string;
	UPSTREAM_SOCKET: boolean;
	DEFAULT_MODEL: string;
	RETRY_ATTEMPTS: number;
	GEMINI_ACCOUNT_MAX_ATTEMPTS: number;
	RETRY_DELAY_SEC: number;
	REQUEST_TIMEOUT_SEC: number;
	REQUEST_BODY_MAX_BYTES: number;
	LOG_REQUESTS: boolean;
	CURRENT_INPUT_FILE_ENABLED: boolean;
	CURRENT_INPUT_FILE_MIN_BYTES: number;
	CURRENT_INPUT_FILE_NAME: string;
	CURRENT_TOOLS_FILE_NAME: string;
	GENERIC_FILE_UPLOAD_MAX_BYTES: number;
	GEMINI_COOKIE: string;
	GEMINI_COOKIES: string;
	SAPISID: string;
	API_KEYS: string;
	ADMIN_PASSWORD: string;
	GEMINI_SESSION_POOL: DurableObjectNamespace<import("./dist/worker").GeminiSessionPool>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./dist/worker");
		durableNamespaces: "GeminiSessionPool";
	}
	interface Env extends __BaseEnv_WorkerBindings {}
}
interface WorkerBindings extends __BaseEnv_WorkerBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "GEMINI_BL" | "GEMINI_ORIGIN" | "UPSTREAM_SOCKET" | "DEFAULT_MODEL" | "RETRY_ATTEMPTS" | "GEMINI_ACCOUNT_MAX_ATTEMPTS" | "RETRY_DELAY_SEC" | "REQUEST_TIMEOUT_SEC" | "REQUEST_BODY_MAX_BYTES" | "LOG_REQUESTS" | "CURRENT_INPUT_FILE_ENABLED" | "CURRENT_INPUT_FILE_MIN_BYTES" | "CURRENT_INPUT_FILE_NAME" | "CURRENT_TOOLS_FILE_NAME" | "GENERIC_FILE_UPLOAD_MAX_BYTES" | "GEMINI_COOKIE" | "GEMINI_COOKIES" | "SAPISID" | "API_KEYS" | "ADMIN_PASSWORD">> {}
}
